version: 2.1

display:
  source_url: https://github.com/Bruno-M44/Python-OC-Lettings-FR
  

orbs:
  python: circleci/python@2.0.3
  docker: circleci/docker@2.0.1

jobs:
  build:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - python/install-packages:
          pip-dependency-file: requirements.txt
          pkg-manager: pip

  test:
    executor: python/default
    steps:
      - checkout
      - run:
          command: |
            pytest
          name: Test

  lint:
    executor: python/default
    steps:
      - checkout
      - run:
          command: flake8

  deploy:
    machine: true
    steps:
      - checkout
      - run:
          name: Push Docker image to Heroku
          command: |
            sudo curl https://cli-assets.heroku.com/install.sh | sh
            HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:login
            HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:push -a $HEROKU_APP_NAME web
            HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:release -a $HEROKU_APP_NAME web

workflows:
  main:
    jobs:
      - build
      - test:
          requires:
            - build
      - lint:
          requires:
            - build
      - docker/publish:
          name: containerize
          image: brunom44/oc-lettings
          tag: $CIRCLE_SHA1
          requires:
            - build
            - test
            - lint
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - containerize
          filters:
            branches:
              only: master
