version: 2.1

orbs:
  python: circleci/python@1.5.0
  heroku: circleci/heroku@1.2.6

executors:
  my-machine:
    machine: true
    working_directory: /tmp/workspace

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: pytest

  build-push-docker:
    executor: my-machine
    steps:
      - checkout
      - run:
          name: Build Docker image
          command: docker build -t $DOCKER_USER/oc-lettings:$CIRCLE_SHA1 .
      - run:
          name: Push Docker Image
          command: |
            echo $DOCKER_TOKEN | docker login -u $DOCKER_USER --password-stdin
            docker tag $DOCKER_USER/oc-lettings:$CIRCLE_SHA1 $DOCKER_USER/oc-lettings:lastest
            docker push $DOCKER_USER/oc-lettings:$CIRCLE_SHA1
            docker push $DOCKER_USER/oc-lettings:lastest

  heroku_deploy:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      # - run:
      #     command: >
      #       echo "Please wait for deployment"
      # - run: heroku config:set DJANGO_SECRET_KEY=$DJANGO_SECRET_KEY -a $HEROKU_APP_NAME
      # - run: heroku config:set DSN_SENTRY=$DSN_SENTRY -a $HEROKU_APP_NAME
      - heroku/deploy-via-git:
          app-name: $HEROKU_APP_NAME
          api-key: HEROKU_API_KEY
      - run:
          name: loading data
          command: python manage.py loaddata data.json

workflows:
  master_commit:
    jobs:
      - build-and-test:
          filters:
            branches:
              only:
                - master
      - build-push-docker:
          requires:
            - build-and-test

      - heroku_deploy:
          requires:
            - build-push-docker

  dev_commit:
    jobs:
      - build-and-test:
          filters:
            branches:
              ignore:
                - master
