version: 2.1

orbs:
  python: circleci/python@1.5.0
  heroku: circleci/heroku@1.2.6

executors:
  my-machine:
    machine: true
    working_directory: /tmp/workspace

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: pytest

  build-push-docker:
    executor: my-machine
    steps:
      - checkout
      - run:
          name: Build Docker image
          command: docker build -t $DOCKER_USER/oc-lettings:$CIRCLE_SHA1 .
      - run:
          name: Push Docker Image
          command: |
            echo $DOCKER_TOKEN | docker login -u $DOCKER_USER --password-stdin
            docker tag $DOCKER_USER/oc-lettings:$CIRCLE_SHA1 $DOCKER_USER/oc-lettings:lastest
            docker push $DOCKER_USER/oc-lettings:$CIRCLE_SHA1
            docker push $DOCKER_USER/oc-lettings:lastest

  heroku_deploy:
    executor: heroku/default
    steps:
      - checkout
      - heroku/deploy-via-git:
          force: true

workflows:
  sample:
    jobs:
      - build-and-test
      - build-push-docker
      - heroku_deploy:
          requires:
            - build-push-docker

