version: 2.1

display:
  source_url: https://github.com/Bruno-M44/Python-OC-Lettings-FR
  

orbs:
  python: circleci/python@0.3.2
  docker: circleci/docker@2.0.1
  heroku: circleci/heroku@1.2.6

jobs:
  build:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache

  test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - run:
          command: pytest

  deploy:
    executor: heroku/default
    steps:
      - checkout
      # Install Heroku if not already installed
      - heroku/install
      # Deploy app to Heroku
      - heroku/deploy-via-git:
          app-name: $HEROKU_APP_NAME
          api-key: HEROKU_API_KEY

workflows:
  main:
    jobs:
      - build
      - test:
          requires:
            - build

      - docker/publish:
          name: containerize
          image: $DOCKER_USER/oc-lettings:lastest
          tag: $CIRCLE_SHA1
          requires:
            - build
            - test
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - containerize
          filters:
            branches:
              only: master
